[workspace]
members = [
    "game",
    "bundlebox"
]

[profile.dev]
opt-level = 3

[profile.dev.package.'*']
opt-level = 3

[profile.release]
codegen-units = 1
opt-level = 3
lto = "fat"

# [patch.crates-io]
# bevy = { path = "../bevy" }
# bevy_rapier2d = { path = "../bevy_rapier/bevy_rapier2d" }
