[workspace]
members = [
    "game"
]

[patch.crates-io]
bevy = { git = "https://github.com/bevyengine/bevy.git", rev = "f6fc76db1da0fa9c6dc67f7b3f0c288904f0eec9" }

[profile.dev]
opt-level = 3

[profile.release]
codegen-units = 1
opt-level = 3
#lto = "fat"
